frr version 10.5
frr defaults traditional
hostname spine1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.11/32
!
interface eth1
 ip address 10.0.0.0/31
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.0.2/31
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.11
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.0.0.0/31 area 0
 network 10.0.0.2/31 area 0
 network 10.255.0.11/32 area 0
!
