frr version 10.5
frr defaults traditional
hostname leaf2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.22/32
!
interface eth1
 ip address 10.0.0.3/31
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.0.7/31
 ip ospf network point-to-point
!
interface eth3
 ip address 192.168.2.1/24
!
router ospf
 ospf router-id 10.255.0.22
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.0.0.2/31 area 0
 network 10.0.0.6/31 area 0
 network 10.255.0.22/32 area 0
 network 192.168.2.0/24 area 0
!
