frr version 10.5
frr defaults traditional
hostname spine2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.12/32
!
interface eth1
 ip address 10.0.0.4/31
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.0.6/31
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.12
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.0.0.4/31 area 0
 network 10.0.0.6/31 area 0
 network 10.255.0.12/32 area 0
!
router bgp 65100
 bgp router-id 10.255.0.12
 no bgp ebgp-requires-policy
 neighbor 10.255.0.21 remote-as 65100
 neighbor 10.255.0.21 update-source lo
 neighbor 10.255.0.22 remote-as 65100
 neighbor 10.255.0.22 update-source lo

 address-family ipv4 unicast
  neighbor 10.255.0.21 activate
  neighbor 10.255.0.22 activate
  neighbor 10.255.0.21 next-hop-self
  neighbor 10.255.0.22 next-hop-self
  neighbor 10.255.0.21 route-reflector-client
  neighbor 10.255.0.22 route-reflector-client
 exit-address-family
!
