frr version 10.5
frr defaults traditional
hostname spine2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.12/32
!
interface eth1
 ip address 10.0.0.4/31
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.0.6/31
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.12
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.0.0.4/31 area 0
 network 10.0.0.6/31 area 0
 network 10.255.0.12/32 area 0
!
