frr version 10.5
frr defaults traditional
hostname edge1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.31/32
!
interface eth1
 ip address 172.16.0.1/31
!
interface eth2
 ip address 172.16.0.3/31
!
ip route 0.0.0.0/0 Null0
!
router bgp 65050
 bgp router-id 10.255.0.31
 no bgp ebgp-requires-policy
 neighbor 172.16.0.0 remote-as 65100
 neighbor 172.16.0.2 remote-as 65100
 !
 address-family ipv4 unicast
  neighbor 172.16.0.0 activate
  neighbor 172.16.0.2 activate
  neighbor 172.16.0.0 default-originate
  neighbor 172.16.0.2 default-originate
 exit-address-family
!